apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      type: demo
  template:
    metadata:
      name: ngnix
      labels:
        type: demo
    spec:
      containers:
        - name: cont1
          image: img1
  
