apiVersion: apps/v1
kind: Deployment
metadata:
  name: demodeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      type: demo
  template:
    metadata:
      name: ngnix
      labels:
        type: demo
    spec:
      containers:
        - name: cont1
          image: sinchana30shettar/img1
          ports:
            - containerPort: 80
            
  
